//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookKeeping.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookKeeping.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About application.
        /// </summary>
        public static string AboutApplication {
            get {
                return ResourceManager.GetString("AboutApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add product.
        /// </summary>
        public static string Add_Product {
            get {
                return ResourceManager.GetString("Add_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main window.
        /// </summary>
        public static string Application_Name {
            get {
                return ResourceManager.GetString("Application_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Application_Ready {
            get {
                return ResourceManager.GetString("Application_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        public static string Barcode {
            get {
                return ResourceManager.GetString("Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge.
        /// </summary>
        public static string Charge {
            get {
                return ResourceManager.GetString("Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter....
        /// </summary>
        public static string DoFilter {
            get {
                return ResourceManager.GetString("DoFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string DoSearch {
            get {
                return ResourceManager.GetString("DoSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods.
        /// </summary>
        public static string Goods {
            get {
                return ResourceManager.GetString("Goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History of goods.
        /// </summary>
        public static string HistoryOfGoods {
            get {
                return ResourceManager.GetString("HistoryOfGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item no..
        /// </summary>
        public static string ItemNo {
            get {
                return ResourceManager.GetString("ItemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of customers.
        /// </summary>
        public static string ListOfCustomers {
            get {
                return ResourceManager.GetString("ListOfCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of products.
        /// </summary>
        public static string ListOfProducts {
            get {
                return ResourceManager.GetString("ListOfProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate.
        /// </summary>
        public static string Order_Calculate {
            get {
                return ResourceManager.GetString("Order_Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place order.
        /// </summary>
        public static string Order_PlaceOrder {
            get {
                return ResourceManager.GetString("Order_PlaceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter item no., barcode or title of product.
        /// </summary>
        public static string Order_SearchPlaceholder {
            get {
                return ResourceManager.GetString("Order_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Order_Subtotal {
            get {
                return ResourceManager.GetString("Order_Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incl. VAT Total.
        /// </summary>
        public static string Order_Total {
            get {
                return ResourceManager.GetString("Order_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total VAT.
        /// </summary>
        public static string Order_TotalVatRate {
            get {
                return ResourceManager.GetString("Order_TotalVatRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order overview.
        /// </summary>
        public static string OrderOverview {
            get {
                return ResourceManager.GetString("OrderOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase of goods.
        /// </summary>
        public static string PurchaseOfGoods {
            get {
                return ResourceManager.GetString("PurchaseOfGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity by default.
        /// </summary>
        public static string QuantityByDefault {
            get {
                return ResourceManager.GetString("QuantityByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remains of goods.
        /// </summary>
        public static string RemainsOfGoods {
            get {
                return ResourceManager.GetString("RemainsOfGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report on the seller.
        /// </summary>
        public static string ReportOnSeller {
            get {
                return ResourceManager.GetString("ReportOnSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale of goods.
        /// </summary>
        public static string SaleOfGoods {
            get {
                return ResourceManager.GetString("SaleOfGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales for the period.
        /// </summary>
        public static string SalesForPeriod {
            get {
                return ResourceManager.GetString("SalesForPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string Select_All {
            get {
                return ResourceManager.GetString("Select_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        public static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thesaurus.
        /// </summary>
        public static string Thesaurus {
            get {
                return ResourceManager.GetString("Thesaurus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time_Utc.
        /// </summary>
        public static string Time_Utc {
            get {
                return ResourceManager.GetString("Time_Utc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of measure.
        /// </summary>
        public static string UnitOfMeasure {
            get {
                return ResourceManager.GetString("UnitOfMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vat rate.
        /// </summary>
        public static string VatRate {
            get {
                return ResourceManager.GetString("VatRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor list.
        /// </summary>
        public static string VendorList {
            get {
                return ResourceManager.GetString("VendorList", resourceCulture);
            }
        }
    }
}
